version: '3'

services:
  app:
    env_file: .env
    environment:
      - DB_HOST=db
    container_name: app
    ports:
      - "${PORT}:${PORT}"
    image: snake-backend
    build: .
    depends_on:
      - db
    volumes:
      - ./public:/home/node/app/public

  db:
    container_name: db
    image: mongo:5.0.3-focal
    volumes:
      - ./data:/data/db

networks:
  app-net: